import { prisma } from "@/lib/prisma";
import { daysLabel } from "@/lib/status";
import { StatusBadge } from "@/components/dashboard/status-badge";
import { ContactActions } from "@/components/clients/contact-actions";
import { RenewalStageControl } from "@/components/clients/renewal-stage";
import Link from "next/link";
import { TableScroll } from "@/components/layout/table-scroll";
const validPeriods = ["hoje", "30", "60", "90", "vencidos", "todos"] as const;
const validProducts = ["E_CPF", "E_CNPJ", "E_PF", "E_PJ"] as const; const validCertificates = ["A1", "A3"] as const; const validStatuses = ["ATIVO", "PROXIMO_VENCIMENTO", "VENCIDO", "RENOVADO"] as const;
export default async function Renewals({ searchParams }: { searchParams: Promise<{ q?: string; periodo?: string; produto?: string; certificado?: string; status?: string }> }) {
 const params=await searchParams; const q=params.q?.trim()||""; const periodo=validPeriods.includes(params.periodo as never)?params.periodo!:"30"; const produto=validProducts.includes(params.produto as never)?params.produto!:"todos"; const certificado=validCertificates.includes(params.certificado as never)?params.certificado!:"todos"; const status=validStatuses.includes(params.status as never)?params.status!:"todos";
 const start=new Date(); start.setHours(0,0,0,0); const end=new Date(start); if(["30","60","90"].includes(periodo))end.setDate(end.getDate()+Number(periodo)); const endToday=new Date(start);endToday.setHours(23,59,59,999); const dates=periodo==="hoje"?{gte:start,lte:endToday}:periodo==="vencidos"?{lt:start}:periodo==="todos"?undefined:{gte:start,lte:end}; const searched=q?{OR:[{orderNumber:{contains:q,mode:"insensitive" as const}},{name:{contains:q,mode:"insensitive" as const}},{legalName:{contains:q,mode:"insensitive" as const}},{cpf:{contains:q}},{cnpj:{contains:q}},{email:{contains:q,mode:"insensitive" as const}}]}:{};
 const clients=await prisma.client.findMany({where:{AND:[dates?{expirationDate:dates}:{},produto!=="todos"?{productType:produto as never}:{},certificado!=="todos"?{certificateType:certificado as never}:{},status!=="todos"?{status:status as never}:{},searched]},orderBy:{expirationDate:"desc"},take:200}); const active=q||periodo!=="30"||produto!=="todos"||certificado!=="todos"||status!=="todos";
 return <><h2 className="text-2xl font-bold mb-2">Renovações</h2><p className="text-slate-500 mb-5">Acompanhe, contate e atualize a situação de cada renovação.</p><form className="flex flex-wrap gap-2 mb-5"><input className="max-w-md" name="q" defaultValue={q} placeholder="Pesquisar cliente, pedido, CPF, CNPJ ou e-mail"/><select name="periodo" defaultValue={periodo} className="w-auto"><option value="hoje">Vencem hoje</option><option value="30">Próximos 30 dias</option><option value="60">Próximos 60 dias</option><option value="90">Próximos 90 dias</option><option value="vencidos">Vencidos</option><option value="todos">Todos</option></select><select name="produto" defaultValue={produto} className="w-auto"><option value="todos">Todos os produtos</option><option value="E_CPF">E-CPF</option><option value="E_CNPJ">E-CNPJ</option><option value="E_PF">E-PF</option><option value="E_PJ">E-PJ</option></select><select name="certificado" defaultValue={certificado} className="w-auto"><option value="todos">Todos os certificados</option><option value="A1">A1</option><option value="A3">A3</option></select><select name="status" defaultValue={status} className="w-auto"><option value="todos">Todos os status</option><option value="ATIVO">Ativo</option><option value="PROXIMO_VENCIMENTO">Próximo do vencimento</option><option value="VENCIDO">Vencido</option><option value="RENOVADO">Renovado</option></select><button className="bg-slate-800 text-white rounded-lg px-4 py-2 text-sm">Filtrar</button>{active&&<Link href="/renovacoes" className="border rounded-lg px-4 py-2 text-sm">Limpar</Link>}</form><div className="bg-white border rounded-xl overflow-hidden"><TableScroll><table><thead><tr><th>Cliente</th><th>Pedido</th><th>Produto</th><th>Identificação</th><th>Modelo</th><th>Emissão</th><th>Vencimento</th><th>Dias restantes</th><th>Etapa comercial</th><th>Status</th><th>Ações</th></tr></thead><tbody>{clients.map(client=><tr key={client.id}><td>{client.name||client.legalName||"—"}</td><td>{client.orderNumber}</td><td>{client.productType}</td><td>{client.cpf||client.cnpj||"—"}</td><td>{client.certificateType}</td><td>{client.issuedAt?.toLocaleDateString("pt-BR")||"—"}</td><td>{client.expirationDate.toLocaleDateString("pt-BR")}</td><td>{daysLabel(client.expirationDate)}</td><td><RenewalStageControl clientId={client.id} stage={client.renewalStage}/></td><td><StatusBadge status={client.status}/></td><td><ContactActions clientId={client.id}/></td></tr>)}{clients.length===0&&<tr><td colSpan={11} className="text-slate-500">Nenhum cliente encontrado neste filtro.</td></tr>}</tbody></table></TableScroll></div></>;
}
