CREATE TYPE "UserRole" AS ENUM ('ADMIN', 'OPERADOR');
CREATE TYPE "RenewalStage" AS ENUM ('PENDENTE', 'CONTATADO', 'NEGOCIACAO', 'RENOVADO', 'RECUSADO');
ALTER TABLE "User" ADD COLUMN "role" "UserRole" NOT NULL DEFAULT 'OPERADOR';
ALTER TABLE "Client" ADD COLUMN "renewalStage" "RenewalStage" NOT NULL DEFAULT 'PENDENTE', ADD COLUMN "estimatedValue" DECIMAL(12,2), ADD COLUMN "notes" TEXT;
UPDATE "User" SET "role" = 'ADMIN' WHERE "id" = (SELECT "id" FROM "User" ORDER BY "createdAt" ASC LIMIT 1);
