import { fail, ok } from "@/lib/api";
import { parseClient, type PreviewRow } from "@/lib/spreadsheet/import";
import { calculateCertificateStatus } from "@/lib/status";
import { calendarDate, expirationFromEmissionDate } from "@/lib/certificates";
import { resolveSalePrice } from "@/lib/sales-pricing";
import { assertFinancialMonthOpen } from "@/lib/financial-period";
import { prisma } from "@/lib/prisma";
import { auth } from "@/auth";
import { audit } from "@/lib/audit";
export async function POST(request:Request){try{const {rows}=await request.json() as {rows?:PreviewRow[]};if(!Array.isArray(rows)||!rows.length)return fail("INVALID_IMPORT","Nenhuma linha disponível para importar.");const session=await auth();const actor=await prisma.user.findUnique({where:{email:session?.user?.email||""},select:{id:true}});const candidates=rows.filter(row=>row.valid&&!row.duplicate);const orders=candidates.map(row=>row.values.orderNumber);const present=new Set((await prisma.client.findMany({where:{orderNumber:{in:orders}},select:{orderNumber:true}})).map(client=>client.orderNumber));let imported=0;const skipped:{line:number;reason:string}[]=[];for(const row of candidates){if(present.has(row.values.orderNumber)){skipped.push({line:row.line,reason:"Pedido já cadastrado"});continue;}const parsed=parseClient(row.values);if(!parsed.success){skipped.push({line:row.line,reason:parsed.error.issues[0].message});continue;}const v=parsed.data;const purchaseDate=v.purchaseDate||new Date();try{await assertFinancialMonthOpen(purchaseDate)}catch(error){skipped.push({line:row.line,reason:error instanceof Error?error.message:"Mês financeiro fechado"});continue;}const issuedAt=v.issuedAt?calendarDate(v.issuedAt):null;const expirationDate=issuedAt?expirationFromEmissionDate(issuedAt,v.certificateType):v.expirationDate;const price=await resolveSalePrice(v.productType,v.certificateType,v.a3Model,purchaseDate);const client=await prisma.client.create({data:{...v,issuedAt,expirationDate,purchaseDate,cnpj:v.cnpj||null,partnerId:v.partnerId||null,a3Model:v.certificateType==="A1"?null:v.a3Model!,estimatedValue:price?.amount,priceRuleId:price?.priceRuleId,status:calculateCertificateStatus(expirationDate)}});await audit({actorUserId:actor?.id,action:"CLIENT_IMPORTED",entity:"Client",entityId:client.id,details:{orderNumber:client.orderNumber,sourceLine:row.line,issuedAt:client.issuedAt?.toISOString()||null}});present.add(v.orderNumber);imported++;}return ok({imported,skipped,ignored:rows.length-candidates.length});}catch(error){console.error("Import failed",error);return fail("IMPORT_FAILED","Não foi possível concluir a importação.")}}
