import { prisma } from "@/lib/prisma";
import Link from "next/link";
import { StatusBadge } from "@/components/dashboard/status-badge";
import { ContactActions } from "@/components/clients/contact-actions";
import { ClientManagementActions } from "@/components/clients/client-management-actions";
import { TableScroll } from "@/components/layout/table-scroll";
import { auth } from "@/auth";

const validPeriods = ["hoje", "30", "60", "90", "vencidos", "todos"] as const;
export default async function Clients({ searchParams }: { searchParams: Promise<{ q?: string; periodo?: string }> }) {
  const params = await searchParams; const q = params.q?.trim() || ""; const periodo = validPeriods.includes(params.periodo as typeof validPeriods[number]) ? params.periodo! : "todos";
  const session = await auth(); const user = session?.user?.email ? await prisma.user.findUnique({ where: { email: session.user.email }, select: { role: true } }) : null; const isOwner = user?.role === "SUPER_ADMIN";
  const today = new Date(); today.setHours(0,0,0,0); const endOfToday = new Date(today); endOfToday.setHours(23,59,59,999); const end = new Date(today); if (["30","60","90"].includes(periodo)) end.setDate(end.getDate() + Number(periodo));
  const expirationWhere = periodo === "hoje" ? { gte:today, lte:endOfToday } : periodo === "vencidos" ? { lt:today } : periodo === "todos" ? undefined : { gte:today, lte:end };
  const searchWhere = q ? { OR: [{ orderNumber: { contains:q, mode:"insensitive" as const } }, { name: { contains:q, mode:"insensitive" as const } }, { legalName: { contains:q, mode:"insensitive" as const } }, { cpf: { contains:q } }, { cnpj: { contains:q } }, { email: { contains:q, mode:"insensitive" as const } }] } : {};
  const clients = await prisma.client.findMany({ take:200, orderBy:{ expirationDate:"desc" }, where:{ AND:[expirationWhere ? { expirationDate:expirationWhere } : {}, searchWhere] } });
  return <><div className="flex flex-wrap justify-between gap-4 items-center mb-6"><h2 className="text-2xl font-bold">Clientes</h2><div className="flex gap-3"><a href="/api/exports/clients" className="border rounded-lg px-4 py-2 text-sm">Exportar Excel</a><Link href="/clientes/novo" className="bg-teal-700 text-white rounded-lg px-4 py-2 text-sm">Novo cliente</Link></div></div><form className="mb-5 flex flex-wrap gap-2 max-w-3xl"><input name="q" defaultValue={q} placeholder="Pesquisar por cliente, pedido, CPF, CNPJ ou e-mail"/><select name="periodo" defaultValue={periodo} className="w-auto"><option value="todos">Todos os vencimentos</option><option value="hoje">Vencem hoje</option><option value="30">Próximos 30 dias</option><option value="60">Próximos 60 dias</option><option value="90">Próximos 90 dias</option><option value="vencidos">Vencidos</option></select><button className="bg-slate-800 text-white rounded-lg px-4 py-2 text-sm">Filtrar</button>{(q||periodo!=="todos")&&<Link href="/clientes" className="border rounded-lg px-4 py-2 text-sm">Limpar</Link>}</form><div className="bg-white border rounded-xl overflow-hidden"><TableScroll><table><thead><tr><th>Cliente</th><th>Pedido</th><th>Produto</th><th>CPF</th><th>Certificado</th><th>Emissão</th><th>Vencimento</th><th>E-mail</th><th>Status</th><th>Ações</th></tr></thead><tbody>{clients.map(client=><tr key={client.id}><td>{client.name||client.legalName||"—"}</td><td>{client.orderNumber}</td><td>{client.productType}</td><td>{client.cpf}</td><td>{client.certificateType}</td><td>{client.issuedAt?.toLocaleDateString("pt-BR")||"—"}</td><td>{client.expirationDate.toLocaleDateString("pt-BR")}</td><td>{client.email}</td><td><StatusBadge status={client.status}/></td><td><div className="flex items-start gap-2"><ContactActions clientId={client.id}/>{isOwner&&<ClientManagementActions clientId={client.id}/>}</div></td></tr>)}{clients.length===0&&<tr><td colSpan={10} className="text-slate-500">Nenhum cliente encontrado.</td></tr>}</tbody></table></TableScroll></div></>;
}
